name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    name: Build Module (Ubuntu PowerShell 7.x)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install PowerShell
      shell: bash
      run: |
        # PowerShell is pre-installed on ubuntu-latest runners
        pwsh --version

    - name: Install dependencies
      shell: pwsh
      run: |
        ./build.ps1 -ResolveDependency

    - name: Build module
      shell: pwsh
      run: |
        ./build.ps1 -Tasks build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: module-build
        path: output/module/
        retention-days: 1

  test-ubuntu:
    name: Test on Ubuntu (PowerShell 7.x)
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: module-build
        path: output/module/

    - name: Install dependencies
      shell: pwsh
      run: |
        ./build.ps1 -ResolveDependency

    - name: Run tests
      shell: pwsh
      run: |
        ./build.ps1 -Tasks test

  test-windows-ps5:
    name: Test on Windows (PowerShell 5.1)
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: module-build
        path: output/module/

    - name: Install dependencies
      shell: powershell
      run: |
        .\build.ps1 -ResolveDependency

    - name: Run tests
      shell: powershell
      run: |
        .\build.ps1 -Tasks test

  test-windows-ps7:
    name: Test on Windows (PowerShell 7.x)
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: module-build
        path: output/module/

    - name: Install dependencies
      shell: pwsh
      run: |
        .\build.ps1 -ResolveDependency

    - name: Run tests
      shell: pwsh
      run: |
        .\build.ps1 -Tasks test
